### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by emoon** [digitalstreamio/resid-rs#1]
Hi,

I wonder what the current status of this project is compared to the C++ version?

**Comment by digitalstreamio** [comment]
All the code has been ported over and is up an running. The one piece that I have been meaning to complete was to create a test suite or a set of test cases to validate the output generated by the rust version matches C++ output. However, even without the test suite I have been able to use it in my zinc project.

Another thing I have on my todo list is to upload package to crates.io which I may be able to get to this or next week.

Either way, if you are interested in using it I would welcome any feedback. 

Thanks

**Comment by emoon** [comment]
Cool. Thanks!

**Comment by digitalstreamio** [comment]
I've updated TODO and uploaded project to crates.io

https://crates.io/crates/resid-rs
