### ISSUE TITLE
Optimization of compute_convolution_fir_unroll

### ISSUE THREAD

**Issue by emoon** [digitalstreamio/resid-rs#2]
Hi,

For fun I took a look at the `compute_convolution_fir_unroll` https://github.com/digitalstreamio/resid-rs/blob/94271cab2567b3a9eded75aa10b2e5f64baa731e/src/sampler.rs#L407-L436 function. Looking at the generated assembly (i stripped the setup code and focused on the innerloop) it gets generated like this

```
LBB0_5:
	movswl	(%rdi), %eax
	movswl	(%rdx), %ebx
	imull	%eax, %ebx
	addl	%ebx, %r10d
	movswl	2(%rdi), %eax
	movswl	2(%rdx), %ebx
	imull	%eax, %ebx
	addl	%ebx, %r11d
	movswl	4(%rdi), %eax
	movswl	4(%rdx), %ebx
	imull	%eax, %ebx
	addl	%ebx, %r14d
	movswl	6(%rdi), %eax
	movswl	6(%rdx), %ebx
	imull	%eax, %ebx
	addl	%ebx, %r15d
	movswl	8(%rdi), %eax
	movswl	8(%rdx), %ebx
	imull	%eax, %ebx
	addl	%ebx, %r12d
	movswl	10(%rdi), %eax
	movswl	10(%rdx), %ebx
	imull	%eax, %ebx
	addl	%ebx, %esi
	movswl	12(%rdi), %eax
	movswl	12(%rdx), %ebx
	imull	%eax, %ebx
	addl	%ebx, %r8d
	movswl	14(%rdi), %eax
	movswl	14(%rdx), %ebx
	imull	%eax, %ebx
	addl	%ebx, %r9d
	addq	$16, %rdx
	addq	$-8, %rcx
	addq	$16, %rdi
	cmpq	$7, %rcx
	ja	LBB0_5
	jmp	LBB0_2
```

I then played around a bit and rewrote the code like this

```Rust
pub fn compute_convolution_zip(sample: &[i16], fir: &[i16]) -> i32 {
    if sample.len() < fir.len() {
        sample.iter().zip(fir.iter())
            .fold(0, |sum, (&s, &f)| sum + (s as i32 * f as i32))
    } else {
        fir.iter().zip(sample.iter())
            .fold(0, |sum, (&f, &s)| sum + (f as i32 * s as i32))
    }
}
```

This code gets generated (now again looking at the innerloop)

```
LBB1_11:
	movq	-24(%rax), %xmm4
	movq	-16(%rax), %xmm5
	movq	-24(%r9), %xmm3
	movq	-16(%r9), %xmm2
	movdqa	%xmm3, %xmm6
	pmulhw	%xmm4, %xmm6
	pmullw	%xmm4, %xmm3
	punpcklwd	%xmm6, %xmm3
	movdqa	%xmm2, %xmm4
	pmulhw	%xmm5, %xmm4
	pmullw	%xmm5, %xmm2
	punpcklwd	%xmm4, %xmm2
	paddd	%xmm0, %xmm3
	paddd	%xmm1, %xmm2
	movq	-8(%rax), %xmm4
	movq	(%rax), %xmm5
	movq	-8(%r9), %xmm0
	movq	(%r9), %xmm1
	movdqa	%xmm0, %xmm6
	pmulhw	%xmm4, %xmm6
	pmullw	%xmm4, %xmm0
	punpcklwd	%xmm6, %xmm0
	movdqa	%xmm1, %xmm4
	pmulhw	%xmm5, %xmm4
	pmullw	%xmm5, %xmm1
	punpcklwd	%xmm4, %xmm1
	paddd	%xmm3, %xmm0
	paddd	%xmm2, %xmm1
	addq	$32, %r9
	addq	$32, %rax
	addq	$-16, %r8
	jne	LBB1_11
```

Now the compiler is able to use vector instructions instead. Hacking up a quick benchmark of this shows

```
running 2 tests
test tests::unroll ... bench:         372 ns/iter (+/- 31)
test tests::zip    ... bench:         152 ns/iter (+/- 5)
```

So the zip version is more than twice as fast. So might be worth considering to use that instead if you can verify that on your side.

**Comment by digitalstreamio** [comment]
This loop is really taxing and I struggled quite a bit trying to figure out how to get it to be performant. I'll plug your changes in tonight and do a bit more testing before merging them in. Thanks for looking into this.

**Comment by emoon** [comment]
Cool :)

**Comment by digitalstreamio** [comment]
Makes sense. I will gladly grab a patch that uses SIMD once that is available in stable. ;)

In the meantime, I pulled and tested your patch and it works great. It actually closes performance gap with C++ version so cheers for helping out with this.

Crates.io update will follow in the next day or two.

**Comment by digitalstreamio** [comment]
@emoon I pushed a commit with initial SIMD support. I was wondering if you could take a look since this stuff is a bit foreign to me. 

You will need beta Rust toolchain or 1.27 when it comes out. It's not on crates.io yet as waiting for Rust stable SIMD support which is a few weeks away. 

Thanks

**Comment by emoon** [comment]
I looked at the code now. I don't have AVX2 in my CPU so I can't test the code but something that might be worth doing is that instead of having a single `v` value have a number of them like `v0`, `v1`, `v2`,`v3` and use that inside the loop so you don't end adding everything to `v` every time. While the CPU does trick to deal with this (as you are writing to the same register the CPU will have to "wait" on operations to complete to it but it does tricks to try to avoid it)

Anyway, I would try to just a set of more values and then after the loop you would do

**Comment by digitalstreamio** [comment]
Ok. Let me give that a shot and try to get some benchmarks up and running. I suppose getting AVX (as apposed to AVX2) would be too hard, so I may throw that in too. Would AVX work for you?

**Comment by emoon** [comment]
AVX would work but I don't think you have the instructions you need for when using AVX1.0. In general these days SSE4.2 is available for many people so trying to use those instructions instead may prove to be better as it would give a speed up for more people (tho the auto vectorizer seems to do a fairly good job currently on that so hard to say what the speed up would be)

**Comment by digitalstreamio** [comment]
I took you suggestion and added SSE4.2 variant as well as made changes to AVX2 to try to pipeline additions across multiple registers. 

I've also benchmarked all 3 variants and the gains look very promising. See results below:


`     
Running target/release/deps/sampler_bench-2427ecf834a910f3
Gnuplot not found, disabling plotting
convolution_fir_avx2    time:   [28.383 ns 28.483 ns 28.620 ns]                                  
                        change: [-26.597% -26.320% -26.057%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 16 outliers among 100 measurements (16.00%)
  7 (7.00%) high mild
  9 (9.00%) high severe

convolution_fir_sse     time:   [48.476 ns 48.521 ns 48.596 ns]                                 
                        change: [-17.864% -14.183% -10.545%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
  4 (4.00%) high mild
  9 (9.00%) high severe

convolution_fir_fallback                                                                            
                        time:   [138.04 ns 138.06 ns 138.09 ns]
                        change: [-2.3414% -1.4764% -0.7637%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 12 outliers among 100 measurements (12.00%)
  3 (3.00%) high mild
  9 (9.00%) high severe
`

**Comment by digitalstreamio** [comment]
Also, for fun I benchmarked the original variant (compute_convolution_fir_unroll) and it took 319ns. Definitely not as nice as the latest numbers. :)

**Comment by emoon** [comment]
Awesome :) Yeah that matches the numbers I saw also

```
running 2 tests
test tests::unroll ... bench:         372 ns/iter (+/- 31)
test tests::zip    ... bench:         152 ns/iter (+/- 5)
```

Looks like the vectorized versions gives a great speed up for sure. A majority of people will be able to run the SSE 4.2 version and it's a nice improvement for sure as well.

**Comment by digitalstreamio** [comment]
Thanks for the suggestions!

**Comment by emoon** [comment]
np :)

Another thing I just came to realize the `is_x86_feature_detected` (implemantion here https://github.com/rust-lang-nursery/stdsimd/blob/master/stdsimd/arch/detect/os/x86.rs that is used in the macro) is perhaps not super heavy to call all the time but I think it would be a good idea to cache the result in a enum so you can just do a match instead of calling the macro every time you call the function.
