### ISSUE TITLE
Using resid-rs for playing SIDs

### ISSUE THREAD

**Issue by emoon** [digitalstreamio/resid-rs#3]
Hi,

For an upcoming project I'm considering using resid-rs instead of the C++ lib to play sid files. Now in order to get this working I also need a 6510/6502 CPU emulator and there are a few of them around so that should be fine.

Now I wonder if there more things I need to take into account here. I.e do I need more parts of C64 emulation in order to get this to work?

Cheers!

**Comment by digitalstreamio** [comment]
Sounds great. You will need a few more pieces to get it to work. Depending upon player routine, in addition to SID you will also need:

* cpu
* memory
* memory mapped i/o

If player does busy loop, that's all you should need. If it uses timers, then you will also need to pull in CIA.

I am very close to uploading to crates.io my other project - zinc64. If it suits your needs, you could try it out for the missing pieces as it is "c64 emulator toolkit with batteries included but swappable", which basically means you can pick and choose whatever components you need and forget about the rest. 

I'll try to put together an example later tonight that would give you a starting point.

Thanks!

**Comment by digitalstreamio** [comment]
Ok. I've put together a quick sample that shows how to set it up with zinc64 emu toolkit.

https://github.com/digitalstreamio/zinc64/blob/master/tests/sid_player_standalone.rs

It needs to be updated with an actual SID player code and you need to do something with the sound_buffer that gets filled in every frame, but I think the general idea is there.

**Comment by emoon** [comment]
Awesome! Thanks :)

**Comment by digitalstreamio** [comment]
I think the sound playback is getting there. I've cleaned up the code and uploaded the new emulator toolkit crate to crates.io. 

https://crates.io/crates/zinc64 

Have fun!

**Comment by emoon** [comment]
Thanks! I will take a look.
