### ISSUE TITLE
Unable to run resid-rs from command line on Mac

### ISSUE THREAD

**Issue by Jonnie-Cache** [digitalstreamio/resid-rs#4]
I'm just looking for a command line sid player and resid is the best. I'm admittedly new to Rust, but I believe I have my environment set up correctly on my Mac. The cargo build command results in some warnings about various unused code. But, it does seem to compile. However, when I run it, it only gives me:

```
Machine:deps user$ ./resid

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
If I pass it an argument such as ```./resid 3545_II.sid``` it does the same thing. No audio is output.

I'm not sure what I'm doing wrong. Any assistance is appreciated!

**Comment by digitalstreamio** [comment]
resid-rs is a library that emulates MOS Technology SID chip used in C64. In itself, it is not a standalone player application. It can be used to create one so if someone is looking for a fun weekend project, this library can come in handy. Thanks!
